### ISSUE TITLE
MoePhoto official dehazing result have some white line with mx.Predict.

### ISSUE THREAD

**Issue by Ken1256** [WolframRhodium/Super-Resolution-Zoo#4]
http://www.imagebam.com/image/4d46c41015403564

Also How to Converting pre-trained pytorch .pkl model to MXNet?(Try MMdnn few hours but no luck)

**Comment by WolframRhodium** [comment]
Hi, 

I have checked the dehazing result produced by official MoePhoto in PyTorch and it does produce white line at the left edge of the image.
Considering that the network is much lightweight, I suggest to feed the whole image to the network to reduce such artifacts. Adding borders to the image before prediction might also help.

Note: I find that I forgot to preprocess the image in the symbol file. You can try [this](https://gist.github.com/WolframRhodium/1868cac2fb0354950ff6e2a9e40ab65e) to test the model. The params file is fine.

---

I convert PyTorch models to MXNet through ONNX. You can check these two tutorials: "[PyTorch to ONNX](https://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html)", "[ONNX to MXNet](https://mxnet.apache.org/tutorials/onnx/super_resolution.html)", and please feel free to contact me if you need any help.
