### ISSUE TITLE
Model performance comparision

### ISSUE THREAD

**Issue by angelorodem** [WolframRhodium/Super-Resolution-Zoo#5]
A table showing the results for each algorithm for the same photos would be a great addition to this repo!

**Comment by WolframRhodium** [comment]
I agree. [Here](https://github.com/kice/vs_mxnet/blob/master/README.md#perforamce) is a basic comparison.

I'm sorry that I'm busy now and I don't have much time to do that myself.

**Comment by angelorodem** [comment]
> I agree. [Here](https://github.com/kice/vs_mxnet/blob/master/README.md#perforamce) is a basic comparison.
> 
> I'm sorry that I'm busy now and I don't have much time to do that myself.

i may submit a pr in the future then
