### ISSUE TITLE
Add the framework of the model in the individual descriptions

### ISSUE THREAD

**Issue by angelorodem** [WolframRhodium/Super-Resolution-Zoo#6]
Some people don't know which framework was used just by looking at the file extensions and some may even be not too easy to find due generic naming (.bin, .params, .json) adding would help newer people.

**Comment by WolframRhodium** [comment]
[MXNet](https://mxnet.incubator.apache.org) is used for all models currently, as stated in the description of this repo.

**Comment by angelorodem** [comment]
True, it was a overlook, sorry.
